#!/bin/bash

set -e

self=$(readlink -f "$0")
selfdir=$(dirname "$self")

dirxx=${selfdir/#$HOME/}
dirdd=${dirxx//\//__}

systemd=$HOME/.config/systemd/user/
claude=$(which claude)

tf=$systemd/$dirdd.timer
sf=$systemd/$dirdd.service

if [ -f "$tf" ] || [ -f "$sf" ]; then
  echo "Error: Already set up. Remove files to unsetup:"
  echo "rm -f \"$tf\" \"$sf\""
  exit 1
fi

cat >$tf <<EOT
[Unit]
Description=Claude Worker Timer for $selfdir

[Timer]
OnUnitInactiveSec=240

[Install]
WantedBy=timers.target
EOT

cat >$sf <<EOF
[Unit]
Description=Claude Worker Service for $selfdir

[Service]
ExecStart=$selfdir/clanker-run

[Install]
WantedBy=default.target
EOF

git --config --local user.name="Claude Worker by Maria"
git --config --local user.email="vibecoding@jmq.cz"
