#!/bin/bash

set -e

self=$(readlink -f "$0")
selfdir=$(dirname "$self")

claude=$(which claude)

dirxx=${selfdir/#$HOME/}
dirdd=${dirxx//\//__}

git config --local user.name "Claude Worker by Maria"
git config --local user.email "vibecoding@jmq.cz"

if which systemctl >/dev/null; then

  systemd=$HOME/.config/systemd/user/

  tf=$systemd/$dirdd.timer
  sf=$systemd/$dirdd.service

  mkdir -p $systemd

  cat >$tf <<EOT
[Unit]
Description=Claude Worker Timer for $selfdir

[Timer]
OnUnitInactiveSec=240

[Install]
WantedBy=timers.target
EOT

  cat >$sf <<EOF
[Unit]
Description=Claude Worker Service for $selfdir

[Service]
ExecStart=$selfdir/clanker-run

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload

else

  CF=$(mktemp)
  crontab -l | grep -v "$selfdir" > $CF
  echo "*/10 * * * * $selfdir/clanker-run" >>$CF
  crontab $CF
  rm $CF

fi
