#!/bin/bash

set -e

self=$(readlink -f "$0")
selfdir=$(dirname "$self")

cd "$selfdir"

touch clanker.lock
flock -n clanker.lock claude \
  --allowed-tools "Bash(git:*), Edit" \
  "proceed as the workflow specifies in CLAUDE.md" \
  </dev/null >>clanker.log 2>&1

if [ "$?" == 1 ]; then echo "Clanker probably still runs."; fi
