#!/bin/bash

set -e

self=$(readlink -f "$0")
selfdir=$(dirname "$self")

cd "$selfdir"

echo "===========" >> clanker.log
date >> clanker.log

touch clanker.lock
flock -n clanker.lock \
	~/.local/bin/claude \
	--no-session-persistence \
	"proceed as the workflow specifies in CLAUDE.md" \
	</dev/null >>clanker.log 2>&1

case "$?" in
  0)  date >>clanker.log ;;
  1)  echo "Clanker probably still runs." >>clanker.log ;;
  *)  date >>clanker.log 
      echo "exit status $?" >>clanker.log ;;
esac
